aliyun:
  oss:
    endpoint: xxxxxxxxxxxxxxxxx
    bucketName: xxxxxxxx
spring:
  application:
    name: tlias-web-manage
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


  output:
    ansi:
      #彩色日志设置
      enabled: always

  servlet:
    multipart:
      # 配置单个文件最大上传大小
      max-file-size: 10MB
      #配置单个请求最大上传大小(一次请求可以上传多个文件)
      max-request-size: 100MB

#mybatis配置
mybatis:
  configuration:
    #配置SQL日志打印在控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名
    map-underscore-to-camel-case: true
